[#3]회원가입  및 로그인 기능구현
f-lab-edu/smart-store pull request #5
Opened 2021-03-09 14:57 UTC by isaac1102

회원가입에 필요한 기본적인 기능구현

2021-03-10 07:44 UTC, f-lab-dev commented on src/main/java/com/project/smartStore/utils/PasswordEncryptor.java
> +		StringBuffer sb = new StringBuffer();
이 객체는 멀티 스레드 환경에서 공유될 가능성이 있나요?

2021-03-10 07:44 UTC, f-lab-dev commented on src/main/java/com/project/smartStore/utils/PasswordEncryptor.java
> +            e.printStackTrace();
이 메소드는 절대 쓰면 안돼는 메소드입니다. 왜일까요?

2021-03-10 07:44 UTC, f-lab-dev commented on src/main/java/com/project/smartStore/utils/PasswordEncryptor.java
> +		byte[] bytes = new byte[a.length + salt.length];
들여쓰기 컨벤션을 지켜주세요~ checkstyle 검사가 필요해보입니다~

2021-03-10 07:44 UTC, f-lab-dev commented on src/main/java/com/project/smartStore/dto/UserDto.java
> +@Setter
이 클래스는 빈 생성자와 setter가 꼭 필요할까요?

2021-03-10 07:44 UTC, f-lab-dev commented on src/main/java/com/project/smartStore/config/DatabaseConfig.java
> +	public SqlSessionFactory sqlSessionFactory(DataSource dataSource)throws Exception{
`SqlSessionFactory`는 어떤 클래스일까요?

2021-03-11 07:48 UTC, f-lab-dev commented
Pull Request 제목도 잘 지어주세요~ `Feature/3/ej`라고 하면 협업하는 사람들이 PR을 알아보기 힘듭니다~

2021-03-11 07:55 UTC, f-lab-dev commented on src/main/java/com/project/smartStore/controller/UserController.java
> +	public HttpStatus loginUser(@RequestBody UserDto user, HttpSession session) {
`feature/3` 은 회원가입 브랜치인데 로그인 관련 작업 내용이 있네요~

2021-03-11 07:55 UTC, f-lab-dev commented on src/main/java/com/project/smartStore/service/UserService.java
> +	public boolean loginUser(UserDto user, HttpSession session);
1. 이런 메소드들 사이에는 개행을 적절히 넣어주면 가독성이 향상됩니다~
2. 접근제한자는 꼭 써줄 필요가 있을까요?

2021-03-11 07:55 UTC, f-lab-dev commented on src/main/java/com/project/smartStore/service/UserServiceImpl.java
> +		return userMapper.findUserByIdAndPassword(result.orElse(null));
Optional을 써주신 점은 좋은데 굳이 이렇게 쿼리를 두번 날려야할까요?

2021-03-11 07:55 UTC, f-lab-dev commented on src/main/java/com/project/smartStore/service/UserServiceImpl.java
> +	public boolean loginUser(UserDto user, HttpSession session) {
`인증`의 책임이 `UserService`에 있는거는 단일책임원칙에 위배되는 것 같네요~

2021-03-11 07:55 UTC, f-lab-dev commented on src/main/java/com/project/smartStore/service/UserServiceImpl.java
> +			session.setAttribute("loginId", result.get().getId());
`"loginId"`와 같은 값들은 상수로 사용하는게 더 재사용성 측면에서 좋을 것 같습니다~

2021-03-12 05:00 UTC, isaac1102 commented on src/main/java/com/project/smartStore/utils/PasswordEncryptor.java
> +		StringBuffer sb = new StringBuffer();
네 해당 클래스는 이용자가 회원가입 시에 비밀번호를 암호화하는 모듈이므로 멀티 스레드 환경에서 사용될 가능성이 있습니다.  음 생각해보니 thread-safe하게 만들거나 서로 공유되지 않는 방법으로 수정하는 것이 맞는 것 같습니다.

2021-03-12 06:18 UTC, isaac1102 commented on src/main/java/com/project/smartStore/dto/UserDto.java
> +@Setter
빈 생성자는 불필요할 것 같고, setter는 개인정보 변경 기능에 필요할 것 같습니다.

2021-03-12 06:26 UTC, isaac1102 commented on src/main/java/com/project/smartStore/config/DatabaseConfig.java
> +	public SqlSessionFactory sqlSessionFactory(DataSource dataSource)throws Exception{
SqlSessionFactory는 SqlSession을 생성하기 위한 필수객체입니다. 여기서 SqlSession은 세션을 한번 생성하여 매핑된 sql구문을 실행/커밋/롤백하는 역할을 합니다.  SqlSessionFactory는 마이바티스 스프링 연동모듈이 자동으로 생성해주며 스프링 트랜잭션 설정에 따라서 자동으로 커밋/롤백을 수행하고 닫힙니다.

2021-03-12 06:27 UTC, isaac1102 commented on src/main/java/com/project/smartStore/controller/UserController.java
> +	public HttpStatus loginUser(@RequestBody UserDto user, HttpSession session) {
네 브랜치 checkout을 실수했습니다ㅠ

2021-03-12 06:41 UTC, isaac1102 commented on src/main/java/com/project/smartStore/service/UserService.java
> +	public boolean loginUser(UserDto user, HttpSession session);
메소드의 사용범위의 확장성을 염두에 두고 고민없이 public으로 했던 것 같습니다. 
지금보니 현재 패키지 외에는 사용되지 않을 것 같네요. 
불필요한 선언이니 수정하도록 하겠습니다~

2021-03-12 07:18 UTC, isaac1102 commented on src/main/java/com/project/smartStore/service/UserServiceImpl.java
> +		return userMapper.findUserByIdAndPassword(result.orElse(null));
이 부분은 제가 작업을 완료하지 못한 것 같아서 수정을 해야 할 것 같습니다. 
애초의 의도는 
1. 로그인 시에 id와 비밀번호를 입력받아 암호화
2. 기존에 저장된 암호화된 비밀번호를 id값으로 select함
3. 1번과 2번을 대조하여 같다면 로그인 처리
방식으로 처리하려고 했습니다.

2021-03-12 09:02 UTC, f-lab-dev reviewed
커밋 메세지를 보니 컨벤션만 맞춘게 아니라 여러 작업을 하셨는데 그 작업들이 잘 드러나게 커밋메세지를 작성해주세요~ `좋은 커밋 메세지 작성하는 법`을 검색해보셔도 좋을 것 같네요

2021-03-12 09:02 UTC, f-lab-dev commented on src/main/java/com/project/smartstore/SmartStoreApplication.java
> +  public static void main(String[] args) {
이 컨벤션은 google style인 것 같은데 들여쓰기가 이렇게 적으면 가독성이 좀 떨어지지 않을까요?
선호님과 협의해서 좀 키워줘도 될 것 같아요

2021-03-12 09:02 UTC, f-lab-dev commented on src/main/java/com/project/smartstore/controller/UserController.java
> +@RequestMapping("/user")
여기는 복수형으로 해주시는게 좋습니다~ 

https://docs.microsoft.com/ko-kr/azure/architecture/best-practices/api-design

2021-03-12 09:02 UTC, f-lab-dev commented on src/main/java/com/project/smartstore/controller/UserController.java
> +    return HttpStatus.CREATED;
이거는 `@ResponseStatus` 어노테이션으로 대체가 가능합니다~ 201을 리턴하신건 좋았네요~

2021-03-12 09:02 UTC, f-lab-dev commented on src/main/java/com/project/smartstore/controller/UserController.java
> +    return HttpStatus.OK;
이렇게 리턴했을 때 Response가 어떻게 오는지도 확인해보셨나요?

2021-03-12 09:02 UTC, f-lab-dev commented on src/main/java/com/project/smartstore/dto/UserDto.java
> +@Setter
여기서는 setter가 꼭 필요한가요?

2021-03-12 09:02 UTC, f-lab-dev commented on src/main/java/com/project/smartstore/utils/PasswordEncryptor.java
> +      StringBuffer sb = new StringBuffer();
이 객체는 여러 스레드에게 공유될 가능성이 있을까요?

2021-03-12 09:02 UTC, f-lab-dev commented on src/main/java/com/project/smartstore/utils/PasswordEncryptor.java
> +      e.printStackTrace();
이 메소드는 절대 쓰면 안돼는 메소드입니다~ 왜일까요?

2021-03-17 11:31 UTC, isaac1102 commented on src/main/java/com/project/smartStore/utils/PasswordEncryptor.java
> +            e.printStackTrace();
1.  예외 발생 시에 스택 정보를 취합하여 가져오게 되는데,  자바의 예외 스택 정보는 로그를 최대 100개까지 프린트하기 때문에 서버의 성능에도 많은 부하를 주게 됩니다.  또한 취합된 정보를 프린트하는 작업도 부하를 유발하게 됩니다.

2021-03-17 12:59 UTC, isaac1102 commented on src/main/java/com/project/smartStore/utils/PasswordEncryptor.java
> +		StringBuffer sb = new StringBuffer();
암호화 절차에 관해 궁금한 점이 있습니다. salt를 사용해서 암호화를 진행한다면 salt정보는 어떻게 관리하는 것이 좋을까요?

2021-03-18 08:10 UTC, f-lab-dev commented on src/main/java/com/project/smartstore/controller/UserController.java
> +  @ResponseStatus(HttpStatus.OK)
기본값은 OK이므로 이것도 생략이 가능합니다~

2021-03-24 13:02 UTC, isaac1102 commented on src/main/java/com/project/smartstore/controller/UserController.java
> +  @ResponseStatus(HttpStatus.OK)
수정했습니다🔥

2021-03-24 13:04 UTC, isaac1102 commented on src/main/java/com/project/smartstore/dto/UserDto.java
> +@Setter
브라우저에서 받아온 비밀번호를 암호화 한 뒤, dto객체에 다시 set할 경우에 사용하고 있습니다.

2021-03-24 13:04 UTC, isaac1102 commented on src/main/java/com/project/smartstore/controller/UserController.java
> +    return HttpStatus.CREATED;
적용했습니다 🔥

2021-03-24 13:05 UTC, isaac1102 commented on src/main/java/com/project/smartstore/controller/UserController.java
> +@RequestMapping("/user")
수정했습니다! ⚡

2021-03-24 13:05 UTC, isaac1102 commented on src/main/java/com/project/smartstore/SmartStoreApplication.java
> +  public static void main(String[] args) {
선호님과 Google Style 컨벤션으로 하는 것으로 결정했습니다~ 😄

2021-03-24 13:06 UTC, isaac1102 commented on src/main/java/com/project/smartStore/service/UserServiceImpl.java
> +			session.setAttribute("loginId", result.get().getId());
적용했습니다 😃

2021-03-24 13:06 UTC, isaac1102 commented on src/main/java/com/project/smartStore/service/UserServiceImpl.java
> +	public boolean loginUser(UserDto user, HttpSession session) {
수정했습니다!

2021-03-24 13:07 UTC, isaac1102 commented on src/main/java/com/project/smartstore/utils/PasswordEncryptor.java
> +      e.printStackTrace();
예외 발생 시에 스택 정보를 취합하여 가져오게 되는데, 자바의 예외 스택 정보는 로그를 최대 100개까지 프린트하기 때문에 서버의 성능에도 많은 부하를 주게 됩니다. 또한 취합된 정보를 프린트하는 작업도 부하를 유발하게 됩니다.

2021-03-25 05:39 UTC, f-lab-dev commented on src/main/java/com/project/smartStore/utils/PasswordEncryptor.java
> +		StringBuffer sb = new StringBuffer();
보통 salt는 외부에서 관리하고 `@Value`를 이용해 주입해주기도 합니다~

2021-03-25 05:42 UTC, f-lab-dev commented on src/main/java/com/project/smartstore/service/UserServiceImpl.java
> +  @Value("${salt}")
`salt`라는 이름만 보고서는 이게 어떤 역할인지 명확히 알 수 없습니다~
`store.enc.salt` 처럼 구조를 잘 잡아보시면 좋을 것 같네요. 제가 드린 예시는 예시일뿐이므로 어떻게 해야 이 salt라는 값의 의미를 잘 전달할 수 있을지 고민해주세요~

그리고 접근제어자도 달아주시면 좋겠습니다. `@Value`는 생성자 주입도 가능하고요

2021-03-29 07:01 UTC, f-lab-dev approved these changes

2021-04-09 02:38 UTC, f-lab-dev commented on src/main/resources/application.properties
> +server.servlet.context-path=/
뭔가 문자가 깨지는것 같은데 확인 한번 부탁드려요~

2021-04-14 13:29 UTC, f-lab-dev commented on pom.xml
> +			<artifactId>lettuce-core</artifactId>
이거는 이미 포함이 되어있습니다~ 어디에 포함되어있는지 알아보시면 좋을 것 같네요

2021-04-14 13:29 UTC, f-lab-dev commented on src/main/java/com/project/smartstore/config/RedisConfig.java
> +	public RedisTemplate<String, Object> redisTemplate(){
RedisTemplate에 대한 주석도 있으면 좋을 것 같아요~

2021-04-14 13:29 UTC, f-lab-dev commented on src/main/java/com/project/smartstore/config/RedisConfig.java
> + *   springSessionRepositoryFilter은  Spring Session에서 지원하는 HttpSession구현을 대체하는 역할을합니다.
👍

2021-04-17 07:10 UTC, sunho-lee approved these changes

2021-04-19 08:21 UTC, isaac1102 commented on pom.xml
> +			<artifactId>lettuce-core</artifactId>
`spring-boot-starter-data-redis` dependency에 포함돼 있는 것 확인하고 추가하였습니다!

2021-04-20 02:11 UTC, f-lab-dev requested changes

2021-04-20 02:11 UTC, f-lab-dev commented on pom.xml
> +        </dependency>
여기도 뭔가 들여쓰기가 이상하네요~

2021-04-21 09:27 UTC, f-lab-dev approved these changes

2021-04-22 01:35 UTC, merged